# =========================================================================
# TCGA Differential Expression Analysis: WGD (1 & 2) vs WGD (0)

# Date: March 15, 2026
# Description:
# This pipeline performs an automated, pan-cancer differential gene expression 
# analysis to evaluate the transcriptional impact of Whole-Genome Doubling (WGD). 
# It compares WGD-positive (1 & 2 doublings) against WGD-negative (0 doublings) 
# primary tumor samples across available TCGA cohorts.
#
# Methodology:
# Designed for high-impact scientific rigor, this script implements:
#   - Raw, unstranded STAR counts queried directly via TCGAbiolinks to ensure strict 
#     data provenance and reproducibility.
#   - The DESeq2 statistical framework for robust differential expression modeling.
#   - Modern Log2 Fold Change (LFC) shrinkage via the 'apeglm' estimator. This 
#     accounts for variance in low-count genes, providing highly reliable effect 
#     sizes suitable for downstream pathway analysis and publication-grade visualization.
#
# Inputs: 
#   - 'Samples_meta_WGD.xlsx': Metadata file containing Sample IDs, Cancer Type, 
#     and Genome_doublings status.
# Outputs:
#   - Shrunken DE results (.tsv) and size-factor normalized counts (.tsv) per cancer type.

# =========================================================================

# Load required libraries
library(TCGAbiolinks)
library(SummarizedExperiment)
library(DESeq2)
library(dplyr)
library(readr)
library(tibble)
library(readxl)
library(apeglm) 

# -------------------------------------------------------------------------
# 1. DEFINE FILE PATHS
# -------------------------------------------------------------------------
metadata_file <- "data/raw/Samples_meta_WGD.xlsx" 

# -------------------------------------------------------------------------
# 2. LOAD & PREPARE METADATA
# -------------------------------------------------------------------------
cat("Processing metadata...\n")
metadata <- read_excel(metadata_file)

meta_clean <- metadata %>%
  dplyr::select(Sample, Type, Genome_doublings) %>%
  dplyr::filter(!is.na(Genome_doublings), !is.na(Type)) %>%
  dplyr::filter(Type == "LUAD") %>% 
  dplyr::mutate(WGD_status = ifelse(Genome_doublings > 0, "WGD_1_2", "WGD_0")) %>%
  dplyr::mutate(WGD_status = factor(WGD_status, levels = c("WGD_0", "WGD_1_2"))) %>%
  dplyr::mutate(Sample = substr(Sample, 1, 15)) # Standardize to 15-char barcode

cancer_types <- unique(meta_clean$Type)
cat("Found", length(cancer_types), "cancer types to process.\n\n")

# -------------------------------------------------------------------------
# 3. LOOP OVER EACH CANCER TYPE
# -------------------------------------------------------------------------

for (cancer in cancer_types) {
  cat("====================================================\n")
  cat("Processing Cancer Type:", cancer, "\n")
  cat("====================================================\n")
  
  # Subset metadata for this specific cancer
  meta_sub <- meta_clean %>% dplyr::filter(Type == cancer)
  
  # Safety Check: Ensure both groups have at least 3 samples
  counts_per_group <- table(meta_sub$WGD_status)
  if (is.na(counts_per_group["WGD_0"]) || counts_per_group["WGD_0"] < 3 ||
      is.na(counts_per_group["WGD_1_2"]) || counts_per_group["WGD_1_2"] < 3) {
    cat("Skipping", cancer, "- Not enough samples in one or both WGD groups.\n")
    cat("Counts:", paste(names(counts_per_group), counts_per_group, sep="=", collapse=", "), "\n\n")
    next
  }
  
  # Format project name for TCGAbiolinks (e.g., "BRCA" -> "TCGA-BRCA")
  tcga_project <- paste0("TCGA-", cancer)
  
  tryCatch({
    # --- A. DOWNLOAD & PREPARE RAW DATA VIA TCGABIOLINKS ---
    cat("Querying GDC for", tcga_project, "STAR counts...\n")
    query <- GDCquery(
      project = tcga_project,
      data.category = "Transcriptome Profiling",
      data.type = "Gene Expression Quantification",
      workflow.type = "STAR - Counts",
      experimental.strategy = "RNA-Seq"
    )
    
    # Downloads files to a local "GDCdata" folder. Caches for future runs.
    GDCdownload(query, directory = "data/raw/GDCdata") 
    se <- GDCprepare(query, directory = "data/raw/GDCdata")
    
    # Extract true unstranded raw integer counts
    raw_counts_mat <- assay(se, "unstranded")
    
    # Extract Gene Annotations directly from the GDC object
    gene_annotations <- as.data.frame(rowData(se)) %>%
      dplyr::select(gene_id, gene_name, gene_type)
    
    # Standardize count matrix barcodes to 15 characters
    colnames(raw_counts_mat) <- substr(colnames(raw_counts_mat), 1, 15)
    
    # Handle potential duplicate samples generated by barcode trimming
    unique_samples <- !duplicated(colnames(raw_counts_mat))
    raw_counts_mat <- raw_counts_mat[, unique_samples]
    
    # --- B. ALIGN METADATA AND COUNTS ---
    # Intersect samples
    shared_samples <- intersect(colnames(raw_counts_mat), meta_sub$Sample)
    if (length(shared_samples) < 6) {
      stop("Not enough matching samples between GDC data and metadata.")
    }
    
    meta_aligned <- meta_sub %>%
      dplyr::filter(Sample %in% shared_samples) %>%
      dplyr::arrange(match(Sample, shared_samples))
    
    counts_aligned <- raw_counts_mat[, meta_aligned$Sample]
    stopifnot(all(colnames(counts_aligned) == meta_aligned$Sample))
    
    write_tsv(meta_aligned, paste0("data/processed/meta_aligned_", cancer, ".tsv"))
    counts_export <- as.data.frame(counts_aligned) %>% 
      tibble::rownames_to_column("gene_id")
    write_tsv(counts_export, paste0("data/processed/counts_aligned_", cancer, "tsv"))
    
    # --- C. RUN DESEQ2 ---
    cat("Running DESeq2...\n")
    
    # Note: If Tumor_Purity is added to metadata later, update design to: ~ Purity + WGD_status
    dds <- DESeqDataSetFromMatrix(
      countData = counts_aligned,
      colData   = data.frame(row.names = meta_aligned$Sample, WGD_status = meta_aligned$WGD_status),
      design    = ~ WGD_status 
    )
    
    # Dynamic pre-filtering: >=10 counts in at least 5% of this specific cohort
    min_samples <- round(0.05 * ncol(dds))
    keep <- rowSums(counts(dds) >= 10) >= min_samples
    dds <- dds[keep, ]
    
    # Execute DE Analysis
    dds <- DESeq(dds, quiet = TRUE)
    
    # --- D. EXTRACT RESULTS & APEGLM SHRINKAGE ---
    # apeglm requires the exact coefficient name. For ~ WGD_status, it is:
    coef_name <- "WGD_status_WGD_1_2_vs_WGD_0" 
    
    cat("Applying modern LFC Shrinkage (apeglm)...\n")
    res_shrunken <- lfcShrink(dds, 
                              coef = coef_name, 
                              type = "apeglm",
                              quiet = TRUE)
    
    
    
    # Format and annotate DE results
    res_df <- as.data.frame(res_shrunken) %>%
      tibble::rownames_to_column("gene_id") %>%
      dplyr::left_join(gene_annotations, by = "gene_id") %>%
      dplyr::relocate(gene_name, gene_type, .after = gene_id) %>%
      dplyr::arrange(padj) # Sort by significance
    
    # Extract size-factor normalized counts for visualization
    cat("Extracting normalized counts...\n")
    norm_counts_df <- as.data.frame(counts(dds, normalized = TRUE)) %>%
      tibble::rownames_to_column("gene_id") %>%
      dplyr::left_join(gene_annotations, by = "gene_id") %>%
      dplyr::relocate(gene_name, gene_type, .after = gene_id)
    
    # --- E. EXPORT RESULTS ---
    # Save as .tsv to prevent Excel from corrupting gene names
    output_file <- paste0("results/DE_WGD_1_2_vs_0_", cancer, ".tsv")
    norm_output_file <- paste0("results/NormCounts_WGD_1_2_vs_0_", cancer, ".tsv")
    
    write_tsv(res_df, output_file)
    write_tsv(norm_counts_df, norm_output_file)
    
    cat("Success! Results and Normalized Counts saved as TSV for:", cancer, "\n\n")
    
  }, error = function(e) {
    cat("ERROR processing", cancer, ":", conditionMessage(e), "\n\n")
  })
  
  # --- F. MEMORY MANAGEMENT ---
  # Strictly clear memory before starting the next cancer type
  rm(meta_sub, query, se, raw_counts_mat, gene_annotations, counts_aligned, dds, res_shrunken, res_df, norm_counts_df)
  gc()
}

cat("Pipeline complete! All valid cancer types have been processed.\n")